# -*- coding: utf-8 -*-
"""02_Modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W97SsRBLIZKFyVxplwQ61vbM1ov9tQ0R

# Arabic Medical QA - Model Comparison

**Task:** Arabic Medical Question Answering (37-class classification)

**Models:**
1. Baseline: TF-IDF + Logistic Regression
2. AraBERTv2 (Reproduction of original paper)
3. CAMeL-BERT (LLM Comparison)

**Dataset:** Arabic Medical Q&A Dataset (Kaggle)

## 1. Setup: GPU, Drive & Libraries
"""

import tensorflow as tf
print("TF Version:", tf.__version__)

device_name = tf.test.gpu_device_name()
print('Found GPU at: {}'.format(device_name) if device_name == '/device:GPU:0' else 'Running on CPU')
!nvidia-smi

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers datasets arabert pyarabic farasapy -q

"""## 2. Load Dataset"""

from datasets import load_dataset
import pandas as pd
import numpy as np

data_path = "/content/drive/MyDrive/Arabic_Medical _Q&A"

# Load CLEAN data (after exploration & cleaning notebook)
raw_datasets = load_dataset('csv', data_files={
    'train':      f'{data_path}/train_clean.csv',
    'validation': f'{data_path}/val_clean.csv',
    'test':       f'{data_path}/test_clean.csv'
})

print(raw_datasets)
df_preview = pd.DataFrame(raw_datasets['train'].select(range(5)))
display(df_preview)

"""## 3. Text Cleaning & Label Encoding"""

import re
import torch
import pyarabic.araby as arab
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight

def clean_sentence(text):
    if not isinstance(text, str):
        return ""
    text = arab.strip_tashkeel(text)
    text = arab.strip_tatweel(text)
    text = re.sub(r"https?:\/\/.*[\r\n]*", " ", text, flags=re.MULTILINE)
    text = re.sub(r"[A-Za-z0-9\n\.\،\(\)\{\}\[\] \\ /+_=%$#@!:;\-*&\'^`|~]", " ", text, flags=re.UNICODE)
    text = re.sub("[\u0625\u0623\u0622\u0671]", "\u0627", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

# Convert to DataFrames
train_df = pd.DataFrame(raw_datasets['train'])
val_df   = pd.DataFrame(raw_datasets['validation'])
test_df  = pd.DataFrame(raw_datasets['test'])

# Clean text
for df in [train_df, val_df, test_df]:
    df['question_clean'] = df['question'].apply(clean_sentence)
    df['answer_clean']   = df['answer'].apply(clean_sentence)
    df['text']           = df['question_clean'] + " [SEP] " + df['answer_clean']

# Encode labels
le = LabelEncoder()
le.fit(train_df['label'])
num_labels = len(le.classes_)
print(f"Number of labels: {num_labels}")
print(f"Labels: {le.classes_}")

for df in [train_df, val_df, test_df]:
    df['label_encoded'] = le.transform(df['label'])

# Compute Class Weights to handle imbalance
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_df['label_encoded']),
    y=train_df['label_encoded']
)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float)
print(f"\nClass weights computed for {len(class_weights)} classes")
print(f"Min weight: {class_weights.min():.3f} | Max weight: {class_weights.max():.3f}")
print(f"\nTrain: {len(train_df):,} | Val: {len(val_df):,} | Test: {len(test_df):,}")

"""## 4. Model 1: Baseline — TF-IDF + Logistic Regression"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report
import time

print("Training Baseline (TF-IDF + Logistic Regression)...")
start = time.time()

# TF-IDF Vectorizer
tfidf = TfidfVectorizer(max_features=50000, ngram_range=(1, 2), analyzer='char_wb')
X_train_tfidf = tfidf.fit_transform(train_df['text'])
X_val_tfidf   = tfidf.transform(val_df['text'])
X_test_tfidf  = tfidf.transform(test_df['text'])

y_train = train_df['label_encoded']
y_test  = test_df['label_encoded']

# Logistic Regression
lr_model = LogisticRegression(max_iter=1000, C=1.0, solver='lbfgs', multi_class='multinomial')
lr_model.fit(X_train_tfidf, y_train)

elapsed = time.time() - start
print(f"Training done in {elapsed:.1f}s")

# Evaluate
y_pred_baseline = lr_model.predict(X_test_tfidf)

baseline_acc  = accuracy_score(y_test, y_pred_baseline)
baseline_f1w  = f1_score(y_test, y_pred_baseline, average='weighted', zero_division=0)
baseline_f1m  = f1_score(y_test, y_pred_baseline, average='macro',    zero_division=0)

print(f"\n=== Baseline Results ===")
print(f"Accuracy:    {baseline_acc:.4f}")
print(f"F1-Weighted: {baseline_f1w:.4f}")
print(f"F1-Macro:    {baseline_f1m:.4f}")

print("\nClassification Report:")
print(classification_report(
    le.inverse_transform(y_test),
    le.inverse_transform(y_pred_baseline),
    zero_division=0
))

"""## 5. Model 2: AraBERTv2 (Reproduction of Original Paper)"""

from arabert.preprocess import ArabertPreprocessor
from transformers import AutoTokenizer

arabert_model_name = "aubmindlab/bert-base-arabertv2"
arabert_prep = ArabertPreprocessor(model_name=arabert_model_name, keep_emojis=False)
arabert_tokenizer = AutoTokenizer.from_pretrained(arabert_model_name)

print("AraBERTv2 tokenizer loaded!")

from datasets import Dataset

def make_hf_dataset(df, prep, tok):
    def preprocess(examples):
        q = [prep.preprocess(t) for t in examples['question_clean']]
        a = [prep.preprocess(t) for t in examples['answer_clean']]
        enc = tok(q, a, truncation=True, padding='max_length', max_length=256)
        enc['label'] = examples['label']  # ← label مش label_encoded
        return enc

    ds = Dataset.from_pandas(
        df[['question_clean','answer_clean','label_encoded']]
        .rename(columns={'label_encoded':'label'})
        .reset_index(drop=True)
    )
    return ds.map(preprocess, batched=True,
                  remove_columns=['question_clean','answer_clean'])

print("Preparing AraBERTv2 datasets...")
arabert_train = make_hf_dataset(train_df, arabert_prep, arabert_tokenizer)
arabert_val   = make_hf_dataset(val_df,   arabert_prep, arabert_tokenizer)
arabert_test  = make_hf_dataset(test_df,  arabert_prep, arabert_tokenizer)
print("Done!")

from transformers import BertForSequenceClassification, Trainer, TrainingArguments

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        'accuracy':    accuracy_score(labels, preds),
        'f1_weighted': f1_score(labels, preds, average='weighted', zero_division=0),
        'f1_macro':    f1_score(labels, preds, average='macro',    zero_division=0)
    }

# Weighted Trainer to handle class imbalance
class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get('logits')
        loss_fn = torch.nn.CrossEntropyLoss(
            weight=class_weights_tensor.to(model.device)
        )
        loss = loss_fn(logits, labels)
        return (loss, outputs) if return_outputs else loss

arabert_model = BertForSequenceClassification.from_pretrained(arabert_model_name, num_labels=num_labels)

arabert_args = TrainingArguments(
    output_dir="./results_arabert",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    warmup_ratio=0.1,
    load_best_model_at_end=True,
    metric_for_best_model="f1_weighted",
    save_total_limit=1,
    fp16=True,
    logging_steps=50,
    logging_dir="./logs_arabert",
)

arabert_trainer = WeightedTrainer(
    model=arabert_model,
    args=arabert_args,
    train_dataset=arabert_train,
    eval_dataset=arabert_val,
    compute_metrics=compute_metrics,
)

print("Training AraBERTv2...")
import datetime
start = datetime.datetime.now()
arabert_trainer.train()
elapsed = datetime.datetime.now() - start
print(f"AraBERTv2 training done in {str(elapsed).split('.')[0]}")

arabert_test_results = arabert_trainer.evaluate(eval_dataset=arabert_test)

arabert_preds_out = arabert_trainer.predict(arabert_test)
arabert_preds = np.argmax(arabert_preds_out.predictions, axis=-1)
arabert_true  = arabert_preds_out.label_ids

arabert_acc = accuracy_score(arabert_true, arabert_preds)
arabert_f1w = f1_score(arabert_true, arabert_preds, average='weighted', zero_division=0)
arabert_f1m = f1_score(arabert_true, arabert_preds, average='macro',    zero_division=0)

print(f"=== AraBERTv2 Results ===")
print(f"Accuracy:    {arabert_acc:.4f}")
print(f"F1-Weighted: {arabert_f1w:.4f}")
print(f"F1-Macro:    {arabert_f1m:.4f}")

print("\nClassification Report:")
print(classification_report(
    le.inverse_transform(arabert_true),
    le.inverse_transform(arabert_preds),
    zero_division=0
))

"""Note: Although the model was trained for 3 epochs, the best checkpoint
 was automatically selected from Epoch 1 based on the highest F1-Weighted score.
 This is handled by load_best_model_at_end=True in TrainingArguments.
 Epoch 1 achieved the best generalization before overfitting occurred.

## 6. Model 3: CAMeL-BERT (LLM Comparison)
"""

from transformers import AutoTokenizer as AT

camel_model_name = "CAMeL-Lab/bert-base-arabic-camelbert-mix"
camel_tokenizer = AT.from_pretrained(camel_model_name)
print("CAMeL-BERT tokenizer loaded!")

def make_hf_dataset_notok(df, tok):
    def preprocess(examples):
        q = examples['question_clean']
        a = examples['answer_clean']
        enc = tok(q, a, truncation=True, padding='max_length', max_length=256)
        enc['label'] = examples['label']
        return enc

    ds = Dataset.from_pandas(df[['question_clean','answer_clean','label_encoded']].rename(
        columns={'label_encoded':'label'}))
    return ds.map(preprocess, batched=True, remove_columns=['question_clean','answer_clean'])

print("Preparing CAMeL-BERT datasets...")
camel_train = make_hf_dataset_notok(train_df, camel_tokenizer)
camel_val   = make_hf_dataset_notok(val_df,   camel_tokenizer)
camel_test  = make_hf_dataset_notok(test_df,  camel_tokenizer)
print("Done!")

from transformers import BertForSequenceClassification as BFSC

camel_model = BFSC.from_pretrained(camel_model_name, num_labels=num_labels)

camel_args = TrainingArguments(
    output_dir="./results_camel",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    warmup_ratio=0.1,
    load_best_model_at_end=True,
    metric_for_best_model="f1_weighted",
    save_total_limit=1,
    fp16=True,
    logging_steps=50,
    logging_dir="./logs_camel",
)

camel_trainer = WeightedTrainer(
    model=camel_model,
    args=camel_args,
    train_dataset=camel_train,
    eval_dataset=camel_val,
    compute_metrics=compute_metrics,
)

print("Training CAMeL-BERT...")
start = datetime.datetime.now()
camel_trainer.train()
elapsed = datetime.datetime.now() - start
print(f"CAMeL-BERT training done in {str(elapsed).split('.')[0]}")

camel_preds_out = camel_trainer.predict(camel_test)
camel_preds = np.argmax(camel_preds_out.predictions, axis=-1)
camel_true  = camel_preds_out.label_ids

camel_acc = accuracy_score(camel_true, camel_preds)
camel_f1w = f1_score(camel_true, camel_preds, average='weighted', zero_division=0)
camel_f1m = f1_score(camel_true, camel_preds, average='macro',    zero_division=0)

print(f"=== CAMeL-BERT Results ===")
print(f"Accuracy:    {camel_acc:.4f}")
print(f"F1-Weighted: {camel_f1w:.4f}")
print(f"F1-Macro:    {camel_f1m:.4f}")

print("\nClassification Report:")
print(classification_report(
    le.inverse_transform(camel_true),
    le.inverse_transform(camel_preds),
    zero_division=0
))

"""## 7. Final Comparison & Visualization"""

import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family'] = 'DejaVu Sans'

# Results table
results = {
    'Model':       ['Baseline\n(TF-IDF + LR)', 'AraBERTv2\n(Reproduction)', 'CAMeL-BERT\n(LLM)'],
    'Accuracy':    [baseline_acc,  arabert_acc,  camel_acc],
    'F1-Weighted': [baseline_f1w,  arabert_f1w,  camel_f1w],
    'F1-Macro':    [baseline_f1m,  arabert_f1m,  camel_f1m],
}

results_df = pd.DataFrame(results)
print("=" * 55)
print("FINAL COMPARISON - Arabic Medical QA (37 classes)")
print("=" * 55)
display(results_df.set_index('Model'))

# ---- Bar Chart ----
fig, ax = plt.subplots(figsize=(12, 6))

x = np.arange(len(results['Model']))
width = 0.25
colors = ['#4C72B0', '#DD8452', '#55A868']

bars1 = ax.bar(x - width, results['Accuracy'],    width, label='Accuracy',    color=colors[0], alpha=0.85)
bars2 = ax.bar(x,          results['F1-Weighted'], width, label='F1-Weighted', color=colors[1], alpha=0.85)
bars3 = ax.bar(x + width,  results['F1-Macro'],    width, label='F1-Macro',    color=colors[2], alpha=0.85)

# Add value labels on bars
for bars in [bars1, bars2, bars3]:
    for bar in bars:
        h = bar.get_height()
        ax.annotate(f'{h:.3f}',
                    xy=(bar.get_x() + bar.get_width() / 2, h),
                    xytext=(0, 4), textcoords="offset points",
                    ha='center', va='bottom', fontsize=9, fontweight='bold')

ax.set_xlabel('Model', fontsize=13)
ax.set_ylabel('Score', fontsize=13)
ax.set_title('Arabic Medical QA — Model Comparison (37 classes)', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(results['Model'], fontsize=11)
ax.set_ylim(0, 1.1)
ax.legend(fontsize=11)
ax.yaxis.grid(True, alpha=0.4)
ax.set_axisbelow(True)

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/Arabic_Medical _Q&A/model_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved to Drive!")

"""## 8. Save Best Model to Drive"""

import pickle

# Save AraBERTv2
arabert_save = "/content/drive/MyDrive/Arabic_Medical _Q&A/arabert_model"
arabert_trainer.save_model(arabert_save)
arabert_tokenizer.save_pretrained(arabert_save)

# Save CAMeL-BERT
camel_save = "/content/drive/MyDrive/Arabic_Medical _Q&A/camel_model"
camel_trainer.save_model(camel_save)
camel_tokenizer.save_pretrained(camel_save)

# Save Label Encoder (shared)
with open(f"{arabert_save}/label_encoder.pkl", 'wb') as f:
    pickle.dump(le, f)

print("All models saved to Drive!")
print(f"AraBERTv2 -> {arabert_save}")
print(f"CAMeL-BERT -> {camel_save}")

import nbformat

file_path = "/content/02_Modeling.ipynb"

with open(file_path, "r", encoding="utf-8") as f:
    nb = nbformat.read(f, as_version=4)

nb.metadata.pop("widgets", None)

for cell in nb.cells:
    if "metadata" in cell:
        cell["metadata"].pop("widgets", None)

with open(file_path, "w", encoding="utf-8") as f:
    nbformat.write(nb, f)

print("Widgets metadata removed completely")

